image: jakzal/phpqa:php8.4

before_script:
  - composer install
  - composer require --dev pheromone/phpcs-security-audit


cache:
  paths:
    - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

SecurityChecker:
  stage: SecurityChecker
  script:
    - vendor/bin/phpcs --extensions=php,inc,lib,module,info --standard=PSR2 ./src
  allow_failure: false

security-checker:
  stage: SecurityChecker
  script:
    - vendor/bin/local-php-security-checker
  allow_failure: false

phpcs:
  stage: CodingStandards
  script:
    - vendor/bin/phpcs --standard=PSR2 --ignore=./src/Kernel.php ./src
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
    - vendor/bin/phpstan analyse ./src
  allow_failure: false

twig-lint:
  stage: CodingStandards
  script:
    - twig-lint lint ./templates
  allow_failure: false

phpunit:
  stage: UnitTests
  script:
    - php bin/phpunit
  allow_failure: false
