image: jakzal/phpqa:php8.8.3.13

before_script:
  - composer install

cache:
  paths:
    - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

SecurityChecker:
  stage: SecurityChecker
  script:
    - phpcs --extensions=php,inc,lib,module,info --standard=Security ./src
  allow_failure: false

security-checker:
  stage: SecurityChecker
  script:
    - local-php-security-checker
  allow_failure: false

phpcs:
  stage: CodingStandards
  script:
      - phpcs --standard=PSR2 --ignore=./src/Kernel.php ./src
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false

twig-lint:
  stage: CodingStandards
  image: php:8.1-cli
  before_script:
    - apt-get update && apt-get install -y unzip git curl
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar require --dev friendsofphp/twig-lint:^1.20  # exemple version récente
  script:
    - php vendor/bin/twig-lint lint ./templates
  allow_failure: false


phpunit:
  stage: UnitTests
  script:
    - php bin/phpunit
  allow_failure: false
