image: jakzal/phpqa:php8.4

before_script:
  - composer install

cache:
  paths:
    - vendor/

stages:
  - SecurityChecker
  - CodingStandards
  - UnitTests

SecurityChecker:
  stage: SecurityChecker
  script:
    - phpcs --extensions=php,inc,lib,module,info --standard=Security ./src
  allow_failure: false

security-checker:
  stage: SecurityChecker
  script:
    - local-php-security-checker
  allow_failure: false

phpcs:
  stage: CodingStandards
  script:
    - phpcbf --standard=PSR2 --ignore=./src/Kernel.php ./src || true
    - phpcs --standard=PSR2 --ignore=./src/Kernel.php --warning-severity=0 ./src
  allow_failure: false

phpstan:
  stage: CodingStandards
  script:
    - phpstan analyse ./src
  allow_failure: false

twig-lint:
  stage: CodingStandards
  script:
    - twig-lint lint ./templates
  allow_failure: false

phpunit:
  stage: UnitTests
  script:
    - php bin/phpunit
  allow_failure: false
